spring:
  h2:
    console:
      path: /h2
  datasource:
    url: jdbc:h2:file:./books/db/books;DATABASE_TO_UPPER=false;
    username: user
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:sql-data/*.sql
      mode: always

